version: '3.9'

services:
  frontend-parser:
    build: ./frontend
    ports:
      - "80:80"
  redis:
    image: redis:6.0.9
    expose:
      - 6379
    ports:
      - published: 6379
        target: 6379

  backend-parser:
    build: ./backend
    ports:
      - "8080:8080"

